# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: pySailingVLM Documentation
author: Zuzanna Wieczorek, Grzegorz Gruszczyński
copyright: "2023"
logo: figures/logo_nowe1.png #/home/zuzanna/Pictures/logo.svg 
exclude_patterns: [_build, other, chapters/results_example_jib_and_mainsail_vlm, README.md]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 600


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/orgSailingVLM/pySailingVLM #https://github.com/orgSailingVLM/vlmbook  # Online location of your book
  path_to_book: https://github.com/orgSailingVLM/vlmbook  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  include-in-header: mathjax.html
parse:
 # myst_amsmath_enable: true
  myst_dmath_double_inline: true
  myst_enable_extensions:
    - amsmath
    - dollarmath

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex


sphinx:
  config:
    latex_elements:
      papersize: a4paper
      pointsize: 12pt
      extrapackages: |
        \usepackage{nicefrac, xfrac}
      maketitle: |
          \sphinxmaketitle
          \clearpage

launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org/v2/gh/orgSailingVLM/pySailingVLM/main?labpath=pySailingVLM%2Fexamples"  # The URL of the BinderHub (e.g., https://mybinder.org)






