# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: pySailingVLm Documentation
author: Grzegorz Gruszczyński, Zuzanna Wieczorek
logo: figures/yacht.png
exclude_patterns: [_build, other, chapters/results_example_jib_and_mainsail_vlm]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/zuza3012/vlmbook  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  include-in-header: mathjax.html
parse:
 # myst_amsmath_enable: true
  myst_dmath_double_inline: true
  myst_enable_extensions:
    - amsmath
    - dollarmath

sphinx:
  config:
    latex_elements:
      extrapackages: |
        \usepackage{nicefrac, xfrac}
      maketitle: |
          \sphinxmaketitle
           
          \clearpage








